version: '3'

services:
  transactions-db:
    image: postgres-with-postgis:17.2
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: transactions
      POSTGRES_PASSWORD: transactions
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transactions"]
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
